app:
  name: L
  version: 0.1
  mode: debug
  canceltimeout: 5

http:
  addr: 127.0.0.1
  port: 8080
  readtimeout: 120
  writetimeout: 120

  log:
    switch: on
    path: ./storage/logs/
    filename: liuqian.log
    level: info
    maxsize: 128
    maxage: 7
    maxbackups: 30
    compress: false